### ISSUE TITLE
인스턴스 및 네트워크 환경 구축

### ISSUE THREAD

**Issue by JJunY8** [soheexz/KDT#1]
인스턴스 구성 yml 파일 설정

**Comment by iJuYoung** [comment]
jenkins-net 오류났어요

**Comment by JJunY8** [comment]
띄어쓰기 오류였습니다.
accessjenkins의 networks:에서
-jenkins-net으로 쓴 오류였습니다.
- jenkins-net으로 수정하여 해결하였습니다.
